type: 'mmdet_yolox'
params:
  accelerator: cuda:0
  conf: 0.6
  min_bbox_area: 100
  model_config: /work/configs/od/mmdet/yolox_x_bytetrack.py
  model_path: /media/home/DanceTrack-orig/.other/bytetrack_models/bytetrack_model.pth.tar
  bytetrack_compat: true
lookup_path: /media/home/DanceTrack-orig/.other/.lookup.json
cache_path: '/workspace/motrack/dancetrack_mmdet_yolox'
oracle: false
