defaults:
  - the_global_config
  - resources: default.yaml
  - dataset: dancetrack.yaml
  - train: bce.yaml
  - eval: default.yaml
  - model_config: mm_tdsp_bboxes_small.yaml
  - path: default.yaml

experiment_name: exp04_fromExp03_HiddenDim128
dataset_name: DanceTrack
